version: 2
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install poetry
      - poetry export --format requirements.txt --without-hashes > requirements.txt
      - pip install -r requirements.txt
